name: kartik

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cron job
        run: npm run backup
